### ISSUE TITLE
Error executing service 🐛 

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Ludy87/xplora_watch#170]
### What version of Integration has the issue?

@Ludy87 since latest update I get around 1-3 times a day following kind of errors

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/xplora_watch/coordinator.py:104
Integration: Xplora® Watch (documentation, issues)
First occurred: 03:03:10 (1 occurrences)
Last logged: 03:03:10

Error executing service: <ServiceCall xplora_watch.see (c:01GSKK44SYDKX1505YCT9J61JV): target=['all']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/xplora_watch/services.py", line 67, in async_see
    await see_service.async_see(kwargs[ATTR_SERVICE_TARGET] if ATTR_SERVICE_TARGET in kwargs else ["all"])
  File "/config/custom_components/xplora_watch/services.py", line 120, in async_see
    await self._coordinator._async_update_data(targets)
  File "/config/custom_components/xplora_watch/coordinator.py", line 113, in _async_update_data
    await self.init(aiohttp_client.async_create_clientsession(self.hass))
  File "/config/custom_components/xplora_watch/coordinator.py", line 104, in init
    await self.controller.init(self.controller._gql_handler.getApiKey(), sec=self.controller._gql_handler.getSecret())
  File "/usr/local/lib/python3.10/site-packages/pyxplora_api/pyxplora_api_async.py", line 70, in init
    raise LoginError(self.error_message)
pyxplora_api.exception_classes.LoginError: Login error: 

## System Information

version | core-2023.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.90
arch | aarch64
timezone | Europe/Bucharest
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1204
Downloaded Repositories | 20

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 15, 2023 at 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 113.9 GB
disk_used | 29.0 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Spotify Connect (0.12.2), Home Assistant Google Drive Backup (0.110.1), File editor (5.5.0), SSH & Web Terminal (13.0.2), Samba share (10.0.0), MariaDB (2.5.2), ESPHome (2023.2.2), Assistant Relay (0.7.4), Mosquitto broker (6.1.3), Zigbee2MQTT (1.30.1-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 12
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 9, 2023 at 04:16
-- | --
current_recorder_run | February 18, 2023 at 19:29
estimated_db_size | 1715.08 MiB
database_engine | mysql
database_version | 10.6.10

</details>

<details><summary>Sonoff</summary>

version | 3.4.0 (5406fa7)
-- | --
cloud_online | 10 / 10
local_online | 5 / 10

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

since latest update I get around 1-3 times a day following kind of errors

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/xplora_watch/coordinator.py:104
Integration: Xplora® Watch (documentation, issues)
First occurred: 03:03:10 (1 occurrences)
Last logged: 03:03:10

Error executing service: <ServiceCall xplora_watch.see (c:01GSKK44SYDKX1505YCT9J61JV): target=['all']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/xplora_watch/services.py", line 67, in async_see
    await see_service.async_see(kwargs[ATTR_SERVICE_TARGET] if ATTR_SERVICE_TARGET in kwargs else ["all"])
  File "/config/custom_components/xplora_watch/services.py", line 120, in async_see
    await self._coordinator._async_update_data(targets)
  File "/config/custom_components/xplora_watch/coordinator.py", line 113, in _async_update_data
    await self.init(aiohttp_client.async_create_clientsession(self.hass))
  File "/config/custom_components/xplora_watch/coordinator.py", line 104, in init
    await self.controller.init(self.controller._gql_handler.getApiKey(), sec=self.controller._gql_handler.getSecret())
  File "/usr/local/lib/python3.10/site-packages/pyxplora_api/pyxplora_api_async.py", line 70, in init
    raise LoginError(self.error_message)
pyxplora_api.exception_classes.LoginError: Login error:

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Not Available
```

**Comment by Ludy87** [comment]
The error is with Xplora, here the service is always interrupted at the same time.

**Comment by smarthomefamilyverrips** [comment]
Ok @Ludy87 thanks, will see if can exclude the error from logs then

**Comment by Ludy87** [comment]
I hope that this is also the case for the other users.

**Comment by Ludy87** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
