### ISSUE TITLE
Error on device update

### ISSUE THREAD

**Issue by thmnxo4** [Ludy87/xplora_watch#35]
Nach Hassio Neustart sind alle Entitäten weg:

Logger: homeassistant.components.device_tracker
Source: custom_components/xplora_watch/device_tracker.py:176
Integration: Geräte-Tracker (documentation, issues)
First occurred: 07:39:51 (1 occurrences)
Last logged: 07:39:51

Error setting up platform legacy xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 251, in async_setup_legacy
    setup = await self.platform.async_setup_scanner(
  File "/config/custom_components/xplora_watch/device_tracker.py", line 114, in async_setup_scanner
    return await scanner.async_init()
  File "/config/custom_components/xplora_watch/device_tracker.py", line 148, in async_init
    await self._async_update()
  File "/config/custom_components/xplora_watch/device_tracker.py", line 169, in _async_update
    await self._update()
  File "/config/custom_components/xplora_watch/device_tracker.py", line 176, in _update
    self._watch_location = await self._controller.getWatchLastLocation(wuid=watch_id, withAsk=True)
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 304, in getWatchLastLocation
    return (await self.loadWatchLocation(wuid=wuid, withAsk=withAsk))[0]["watch_last_location"]
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 212, in loadWatchLocation
    raise FunctionError(sys._getframe().f_code.co_name)
pyxplora_api.exception_classes.FunctionError: Xplora API call finally failed with response: loadWatchLocation

Logger: homeassistant.components.binary_sensor
Source: custom_components/xplora_watch/binary_sensor.py:121
Integration: Binärsensor (documentation, issues)
First occurred: 07:39:47 (1 occurrences)
Last logged: 07:39:47

xplora_watch: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 170, in async_update
    await self.__update()
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 149, in __update
    self.__default_attr(await self.__isSafezone())
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 121, in __isSafezone
    if await self._controller.getWatchIsInSafeZone(wuid=self._watch_id):
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 313, in getWatchIsInSafeZone
    return (await self.getWatchLocate(wuid))["isInSafeZone"]
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 307, in getWatchLocate
    return (await self.loadWatchLocation(wuid=wuid))[0]
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 212, in loadWatchLocation
    raise FunctionError(sys._getframe().f_code.co_name)
pyxplora_api.exception_classes.FunctionError: Xplora API call finally failed with response: loadWatchLocation

Logger: homeassistant.components.sensor
Source: custom_components/xplora_watch/sensor.py:116
Integration: Sensor (documentation, issues)
First occurred: 07:39:47 (1 occurrences)
Last logged: 07:39:47

xplora_watch: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/xplora_watch/sensor.py", line 142, in async_update
    await self.__update()
  File "/config/custom_components/xplora_watch/sensor.py", line 116, in __update
    charging = await self._controller.getWatchIsCharging(wuid=self._watch_id)
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 218, in getWatchIsCharging
    if (await self.loadWatchLocation(wuid=wuid))[0]["watch_charging"]:
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 212, in loadWatchLocation
    raise FunctionError(sys._getframe().f_code.co_name)
pyxplora_api.exception_classes.FunctionError: Xplora API call finally failed with response: loadWatchLocation

Logger: homeassistant.components.binary_sensor
Source: custom_components/xplora_watch/binary_sensor.py:126
Integration: Binärsensor (documentation, issues)
First occurred: 07:39:47 (1 occurrences)
Last logged: 07:39:47

xplora_watch: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 170, in async_update
    await self.__update()
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 158, in __update
    self.__default_attr(await self.__isCharging())
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 126, in __isCharging
    if await self._controller.getWatchIsCharging(wuid=self._watch_id):
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 218, in getWatchIsCharging
    if (await self.loadWatchLocation(wuid=wuid))[0]["watch_charging"]:
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 212, in loadWatchLocation
    raise FunctionError(sys._getframe().f_code.co_name)
pyxplora_api.exception_classes.FunctionError: Xplora API call finally failed with response: loadWatchLocation

**Comment by Ludy87** [comment]
Welche Version von Hassos verwendest du? Hattest du ein Update?

**Comment by thmnxo4** [comment]
2022.5.3

Hatte ich upgedated im Zuge der Sache mit HACS.

**Comment by Ludy87** [comment]
Kannst du yaml Files editieren oder gibt es dort auch Probleme?

**Comment by thmnxo4** [comment]
Kann ich editieren

**Comment by Ludy87** [comment]
Dann restart Hassos nochmals

**Comment by thmnxo4** [comment]
Fehler sind weiterhin da

**Comment by Ludy87** [comment]
Und die Xplora App funktioniert, mit den gleichen Login Daten?

**Comment by Ludy87** [comment]
Okay, ich habe den Fehler lokalisieren können, ein Fix wird schnellstmöglich kommen. Das Problem ist die Bereitstellung von Xplora selber, da keine Daten sporadisch bereitgestellt werden - beobachten konnte ich den Zustand, wenn die Uhr mehrere Stunden nicht eingeschaltet war.

**Comment by Ludy87** [comment]
Sollte behoben sein mit: [v1.0.36](https://github.com/Ludy87/xplora_watch/releases/tag/v1.0.36)

**Comment by thmnxo4** [comment]
Weiterhin Fehler:

Logger: homeassistant.components.device_tracker
Source: custom_components/xplora_watch/device_tracker.py:176
Integration: Geräte-Tracker (documentation, issues)
First occurred: 07:39:30 (1 occurrences)
Last logged: 07:39:30

Error setting up platform legacy xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 251, in async_setup_legacy
    setup = await self.platform.async_setup_scanner(
  File "/config/custom_components/xplora_watch/device_tracker.py", line 114, in async_setup_scanner
    return await scanner.async_init()
  File "/config/custom_components/xplora_watch/device_tracker.py", line 148, in async_init
    await self._async_update()
  File "/config/custom_components/xplora_watch/device_tracker.py", line 169, in _async_update
    await self._update()
  File "/config/custom_components/xplora_watch/device_tracker.py", line 176, in _update
    self._watch_location = await self._controller.getWatchLastLocation(wuid=watch_id, withAsk=True)
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 309, in getWatchLastLocation
    _loadWatchLocation = await self.loadWatchLocation(wuid=wuid, withAsk=withAsk)
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 214, in loadWatchLocation
    raise FunctionError(sys._getframe().f_code.co_name)
pyxplora_api.exception_classes.FunctionError: Xplora API call finally failed with response: loadWatchLocation


Logger: homeassistant.components.binary_sensor
Source: custom_components/xplora_watch/binary_sensor.py:121
Integration: Binärsensor (documentation, issues)
First occurred: 07:39:30 (1 occurrences)
Last logged: 07:39:30

xplora_watch: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 170, in async_update
    await self.__update()
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 149, in __update
    self.__default_attr(await self.__isSafezone())
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 121, in __isSafezone
    if await self._controller.getWatchIsInSafeZone(wuid=self._watch_id):
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 328, in getWatchIsInSafeZone
    return (await self.getWatchLocate(wuid)).get("isInSafeZone", False)
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 317, in getWatchLocate
    _loadWatchLocation = await self.loadWatchLocation(wuid=wuid)
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 214, in loadWatchLocation
    raise FunctionError(sys._getframe().f_code.co_name)
pyxplora_api.exception_classes.FunctionError: Xplora API call finally failed with response: loadWatchLocation


Logger: homeassistant.components.binary_sensor
Source: custom_components/xplora_watch/binary_sensor.py:126
Integration: Binärsensor (documentation, issues)
First occurred: 07:39:29 (1 occurrences)
Last logged: 07:39:29

xplora_watch: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 170, in async_update
    await self.__update()
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 158, in __update
    self.__default_attr(await self.__isCharging())
  File "/config/custom_components/xplora_watch/binary_sensor.py", line 126, in __isCharging
    if await self._controller.getWatchIsCharging(wuid=self._watch_id):
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 220, in getWatchIsCharging
    if (await self.loadWatchLocation(wuid=wuid))[0].get("watch_charging", False):
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 214, in loadWatchLocation
    raise FunctionError(sys._getframe().f_code.co_name)
pyxplora_api.exception_classes.FunctionError: Xplora API call finally failed with response: loadWatchLocation

**Comment by thmnxo4** [comment]
Die Entities sind wieder drin. Es gab allerdings keine Veränderung auf meiner Seite.

**Comment by Ludy87** [comment]
Bin fast der Überzeugung, dass der Dienst von Xplora schlecht ist. Bei meinen beiden Uhr ist seit drei Wochen keine vernünftige Ortung möglich. Die GPS bestimmt ist mangelhaft, so das die Koordinaten per Cell kommt. Die Differenzen liegen bei fast 10km
