### ISSUE TITLE
🐛 Fail to configure integration after upgrade to 2.0.8

### ISSUE THREAD

**Issue by lakofsth** [Ludy87/xplora_watch#76]
## System Information

version | core-2022.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Helsinki
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4880
Installed Version | 1.27.2
Stage | running
Available Repositories | 1117
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 12 August 2023 at 03:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-west-2-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.09.1
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 229.2 GB
disk_used | 11.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Terminal & SSH (9.6.1), Z-Wave JS UI (1.0.1), Home Assistant Google Drive Backup (0.108.4), Glances (0.16.0), PS5 MQTT (1.1.0), Mosquitto broker (6.1.3), Z-Wave JS (0.1.73), RPC Shutdown (2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 4
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 September 2022 at 08:26
-- | --
current_recorder_run | 2 October 2022 at 14:14
estimated_db_size | 1961.62 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

![image](https://user-images.githubusercontent.com/46561994/193451275-eaccb284-87dc-42a3-9dd0-d7c50461db65.png)

No settings have changed, integration was working in 2.0.6. Entities become unavailable, I try to reconfigure the integration and can't get past above error message.

### Reproduction steps

1. Have a working integration v2.0.6
2. Update to 2.0.8 in HACS
3. Try to configure the integration
...

### Debug logs

```text
2022-10-02 14:27:15.969 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xplora_watch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-02 14:27:26.100 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {<redacted> 'xplora_watch', <redacted>}
2022-10-02 14:27:41.914 INFO (MainThread) [homeassistant.setup] Setting up xplora_watch
2022-10-02 14:27:41.915 DEBUG (MainThread) [custom_components.xplora_watch] Set up the Xplora® Watch Version 2 component.
2022-10-02 14:27:41.915 INFO (MainThread) [homeassistant.setup] Setup of domain xplora_watch took 0.0 seconds
2022-10-02 14:27:41.979 DEBUG (MainThread) [custom_components.xplora_watch] Configure based on config entry.
2022-10-02 14:27:48.265 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Fetch data from Xplora®: 6130339
2022-10-02 14:27:48.807 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] load address from openstreetmap.org
2022-10-02 14:27:48.808 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Finished fetching xplora_watch-8147 data in 4.787 seconds (success: True)
2022-10-02 14:27:51.459 DEBUG (MainThread) [custom_components.xplora_watch.helper] services.yaml path: /config/custom_components/xplora_watch/services.yaml
2022-10-02 14:27:51.470 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.xplora_watch
2022-10-02 14:27:51.474 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.xplora_watch
2022-10-02 14:27:51.484 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.xplora_watch
2022-10-02 14:27:51.487 INFO (MainThread) [homeassistant.components.switch] Setting up switch.xplora_watch
2022-10-02 14:27:51.503 INFO (MainThread) [homeassistant.components.notify] Setting up notify.xplora_watch
2022-10-02 14:27:51.505 DEBUG (SyncWorker_0) [custom_components.xplora_watch.notify] init Notify Service
2022-10-02 14:27:51.741 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up xplora_watch platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xplora_watch/binary_sensor.py", line 63, in async_setup_entry
entities.append(XploraBinarySensor(config_entry, coordinator, ward, sw_version, uid, description))
File "/config/custom_components/xplora_watch/binary_sensor.py", line 87, in __init__
if "=" in _wuid:
TypeError: argument of type 'NoneType' is not iterable
2022-10-02 14:27:51.752 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up xplora_watch platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xplora_watch/sensor.py", line 50, in async_setup_entry
entities.append(XploraSensor(config_entry, coordinator, ward, sw_version, uid, description))
File "/config/custom_components/xplora_watch/sensor.py", line 74, in __init__
if "=" in _wuid:
TypeError: argument of type 'NoneType' is not iterable
2022-10-02 14:27:51.989 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up xplora_watch platform for device_tracker
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xplora_watch/device_tracker.py", line 58, in async_setup_entry
XploraSafezoneTracker(hass, config_entry, safeZone, coordinator, ward, sw_version, uid)
File "/config/custom_components/xplora_watch/device_tracker.py", line 88, in __init__
if "=" in _wuid:
TypeError: argument of type 'NoneType' is not iterable
2022-10-02 14:27:52.463 ERROR (MainThread) [homeassistant.components.switch] Error while setting up xplora_watch platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xplora_watch/switch.py", line 50, in async_setup_entry
XploraSilentSwitch(config_entry, silent, coordinator, ward, sw_version, uid, description)
File "/config/custom_components/xplora_watch/switch.py", line 151, in __init__
if "=" in _wuid:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Ludy87** [comment]
Fixed https://github.com/Ludy87/xplora_watch/releases/tag/v2.0.11
